### ISSUE TITLE
typo in template.js

### ISSUE THREAD

**Issue by init-areinhard** [philip-hartmann/storybook-typo3fluid#2]
<pre>
===================================================================
diff --git a/node_modules/storybook-typo3fluid/dist/typo3fluid/template.js b/node_modules/storybook-typo3fluid/dist/typo3fluid/template.js
--- a/node_modules/storybook-typo3fluid/dist/typo3fluid/template.js	
+++ b/node_modules/storybook-typo3fluid/dist/typo3fluid/template.js	(date 1713454424250)
@@ -13,7 +13,7 @@
     _ref$api = _ref.api,
     api = _ref$api === void 0 ? {} : _ref$api;
   var apiUrl = (_ref2 = (_api$url = api == null ? void 0 : api.url) != null ? _api$url : process.env.STORYBOOK_TYPO3FLUID_API_URL) != null ? _ref2 : '';
-  var apiPassword = (_ref3 = (_api$password = api == null ? void 0 : api.password) != null ? _api$password : process.env.STORYBOOK_TYPO3FLUID_API_URL) != null ? _ref3 : '';
+  var apiPassword = (_ref3 = (_api$password = api == null ? void 0 : api.password) != null ? _api$password : process.env.STORYBOOK_TYPO3FLUID_API_PASSWORD) != null ? _ref3 : '';
   if (!apiUrl) {
     return 'No TYPO3 Fluid API URL set!';
   }
   </pre>

**Comment by philip-hartmann** [comment]
Thanks @init-areinhard for opening an issue. I fixed the issue and published version 0.2.1.

In the future please describe the problem and create a pull request instead of posting the diff directly.
